#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path:       /
    controller: App\Controller\HomeController::index

connexion:
    path:       /connexion/
    controller: App\Controller\SecurityController::connexion

inscription:
    path:       /inscription/
    controller: App\Controller\Registration::register

dashboard:
    path:       /dashboard/
    controller: App\Controller\DashboardController::index

new-project:
    path:       /dashboard/new-project/
    controller: App\Controller\ProjectController::newProject

gros-oeuvre:
    path:       /dashboard/my-project/{id}/gros-oeuvre
    controller: App\Controller\GrosOeuvreController::view

second-oeuvre:
    path:       /dashboard/my-project/{id}/second-oeuvre
    controller: App\Controller\SecondOeuvreController::view

etude-sol:
    path:       /dashboard/my-project/{id}/gros-oeuvre/etude-sol
    controller: App\Controller\GrosOeuvreController::etudeSol
    
excavation:
    path:       /dashboard/my-project/{id}/gros-oeuvre/excavation
    controller: App\Controller\GrosOeuvreController::excavation
    
vrd:
    path:       /dashboard/my-project/{id}/gros-oeuvre/vrd
    controller: App\Controller\GrosOeuvreController::vrd
    
fondation:
    path:       /dashboard/my-project/{id}/gros-oeuvre/fondations
    controller: App\Controller\GrosOeuvreController::fondation
    
plancher:
    path:       /dashboard/my-project/{id}/gros-oeuvre/plancher
    controller: App\Controller\GrosOeuvreController::plancher
prep-terrain:
    path:       /dashboard/my-project/{id}/gros-oeuvre/prep-terrain
    controller: App\Controller\GrosOeuvreController::PreparationEtAcces
soubassement:
    path:       /dashboard/my-project/{id}/gros-oeuvre/soubassement
    controller: App\Controller\GrosOeuvreController::Soubassement
elevation:
    path:       /dashboard/my-project/{id}/gros-oeuvre/elevation
    controller: App\Controller\GrosOeuvreController::Elevation    

charpente:
    path:       /dashboard/my-project/{id}/gros-oeuvre/charpente
    controller: App\Controller\GrosOeuvreController::charpente
toiture:
    path:       /dashboard/my-project/{id}/gros-oeuvre/toiture
    controller: App\Controller\GrosOeuvreController::toiture
menuiserie:
    path:       /dashboard/my-project/{id}/menuiserie
    controller: App\Controller\GrosOeuvreController::menuiserie
climatisation:
    path:       /dashboard/my-project/{id}/climatisation
    controller: App\Controller\SecondOeuvreController::climatisation
domotique:
    path:       /dashboard/my-project/{id}/domotique
    controller: App\Controller\SecondOeuvreController::domotique
    
ventilation:
    path:       /dashboard/my-project/{id}/second-oeuvre/ventilation
    controller: App\Controller\SecondOeuvreController::ventilation  

cloisons:
    path:       /dashboard/my-project/{id}/second-oeuvre/cloisons
    controller: App\Controller\SecondOeuvreController::cloison   

evacuation:
    path:       /dashboard/my-project/{id}/second-oeuvre/evacuation-fumees
    controller: App\Controller\SecondOeuvreController::evacuation   

menuiseriesInt:
    path:       /dashboard/my-project/{id}/second-oeuvre/menuiseries-interieures
    controller: App\Controller\SecondOeuvreController::menuiseriesInt
    
escaliers:
    path:       /dashboard/my-project/{id}/second-oeuvre/escaliers
    controller: App\Controller\SecondOeuvreController::escaliers
    
plomberie:
    path:       /dashboard/my-project/{id}/second-oeuvre/plomberie
    controller: App\Controller\SecondOeuvreController::plomberie
    
electricite:
    path:       /dashboard/my-project/{id}/second-oeuvre/electricite
    controller: App\Controller\SecondOeuvreController::electricite

enduit:
    path:       /dashboard/my-project/{id}/second-oeuvre/enduit
    controller: App\Controller\SecondOeuvreController::enduit
isolation:
    path:       /dashboard/my-project/{id}/second-oeuvre/isolation
    controller: App\Controller\SecondOeuvreController::isolation

revetement:
    path:       /dashboard/my-project/{id}/second-oeuvre/revetement
    controller: App\Controller\SecondOeuvreController::revetement

listeAdmin:
    path:       /dashboard/projetsAdmin
    controller: App\Controller\AdminController::projetAdmin

listeMembreAdmin:
    path:       /dashboard/membresAdmin
    controller: App\Controller\AdminController::listeMembreAdmin

logout:
    path: /deconnexion 
